(include_subdirs unqualified)

(rule
  (target version.ml)
  (action
    (write-file %{target}
      "let version = \"%{version:sageboot}\"")
  )
)

(rule
  (target lexer.ml)
  (deps front/lexer.mll)
  (action
    (chdir %{workspace_root}
      (run %{bin:ocamllex} -q -o %{target} %{deps})
    )
  )
)

(executable
  (name main)
  (public_name sageboot)
)
