(lang dune 3.24)

(name sageboot)

(generate_opam_files true)

(source (github mintonaut/sage-lang))
(authors "Mintonaut")
(maintainers "Mintonaut")
(license GNU GLPv3)

(package
 (name sageboot)
 (synopsis "Boot compiler for the Sage programming language")
 (depends ocaml unix)
)

